name: release
on:
  push:
    tags:
      - '**'
env:
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  OOSRH_USERNAME: ${{ secrets.OOSRH_USERNAME }}
  OOSRH_PASSWORD: ${{ secrets.OOSRH_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: OOSRH_USERNAME # env variable for username in deploy
          server-password: OOSRH_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_KEY_SECRET }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Set the release version
        run: mvn semver-release:version-release
      - name: Deploy release
        run: mvn deploy -DskipTests -Prelease